# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "active_zuora"
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["anfleene"]
  s.date = "2012-01-20"
  s.description = "A client for Zuora API"
  s.email = "anfleene@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Rakefile",
    "VERSION",
    "active_zuora.gemspec",
    "custom_fields.yml",
    "lib/active_zuora.rb",
    "lib/zuora/ZUORA.rb",
    "lib/zuora/ZUORADriver.rb",
    "lib/zuora/ZUORAMappingRegistry.rb",
    "lib/zuora/ZuoraServiceClient.rb",
    "lib/zuora/account.rb",
    "lib/zuora/api.rb",
    "lib/zuora/contact.rb",
    "lib/zuora/rate_plan.rb",
    "lib/zuora/rate_plan_data.rb",
    "lib/zuora/subscribe_options.rb",
    "lib/zuora/subscribe_request.rb",
    "lib/zuora/subscribe_with_existing_account_request.rb",
    "lib/zuora/subscription.rb",
    "lib/zuora/subscription_data.rb",
    "lib/zuora/zobject.rb",
    "lib/zuora_client.rb",
    "lib/zuora_interface.rb"
  ]
  s.homepage = "http://github.com/anfleene/active_zuora"
  s.require_paths = ["lib"]
  s.requirements = ["none"]
  s.rubygems_version = "1.8.10"
  s.summary = "Active Zuora"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<soap4r>, [">= 1.5.8"])
      s.add_runtime_dependency(%q<json_pure>, [">= 1.4.6"])
    else
      s.add_dependency(%q<soap4r>, [">= 1.5.8"])
      s.add_dependency(%q<json_pure>, [">= 1.4.6"])
    end
  else
    s.add_dependency(%q<soap4r>, [">= 1.5.8"])
    s.add_dependency(%q<json_pure>, [">= 1.4.6"])
  end
end

